import { adminRoot } from "./defaultValues";

const data = [
  {
    id: "home",
    icon: "simple-icon-home",
    label: "Home",
    to: `${adminRoot}/home`,
  },
  {
    id: "tools",
    icon: "simple-icon-wrench",
    label: "Apps",
    to: `${adminRoot}/utility-bill`,
    permission: "tools",
    subs: [
      {
        icon: "simple-icon-chart",
        label: "Admissions",
        to: `${adminRoot}/assessment`,
        permission: "assessment",
        // permission: [UserRole.Admin],
      },
      {
        icon: "iconsminds-building",
        label: "Classrooms",
        to: `${adminRoot}/support/faq`,
        // permission: [UserRole.Admin],
      },
      {
        icon: "simple-icon-clock",
        label: "Student Attendance",
        to: `${adminRoot}/attendance`,
        // permission: [UserRole.Admin],
      },
      {
        icon: "simple-icon-notebook",
        label: "Student Activity",
        to: `${adminRoot}/attendance`,
        // permission: [UserRole.Admin],
      },
      {
        icon: "simple-icon-notebook",
        label: "CBT",
        to: `${adminRoot}/attendance`,
        // permission: [UserRole.Admin],
      },
      {
        icon: "simple-icon-chart",
        label: "Assessment",
        to: `${adminRoot}/assessment`,
        permission: "assessment",
        // permission: [UserRole.Admin],
      },
      {
        icon: "simple-icon-chart",
        label: "parent care",
        to: `${adminRoot}/assessment`,
        permission: "assessment",
        // permission: [UserRole.Admin],
      },
      // {
      //   icon: "simple-icon-clock",
      //   label: "Teacher Attendance",
      //   to: `${adminRoot}/support/ticket`,
      //   // permission: [UserRole.Admin],
      // },
    ],
  },
  // {
  //   id: "notification",
  //   icon: "simple-icon-bell",
  //   label: "Forum",
  //   to: `${adminRoot}/history`,
  // },
  // {
  //   id: "staff",
  //   icon: "iconsminds-business-man-woman",
  //   label: "Admissions",
  //   to: `${adminRoot}/staffs`,
  //   permission: "staff",
  // },
  {
    id: "studnts",
    icon: "iconsminds-students",
    label: "Students",
    to: `${adminRoot}/students`,
    permission: "student",
  },
  {
    id: "staff",
    icon: "iconsminds-business-man-woman",
    label: "Staffs",
    to: `${adminRoot}/staffs`,
    permission: "staff",
  },
  {
    id: "parent",
    icon: "iconsminds-affiliate",
    label: "Parents",
    to: `${adminRoot}/parents`,
    permission: "parent",
  },
  // {
  //   id: "assessment",
  //   icon: "simple-icon-chart",
  //   label: "Assessment",
  //   to: `${adminRoot}/assessment`,
  //   permission: "assessment",
  //   // subs: [
  //   //   {
  //   //     icon: "simple-icon-chart",
  //   //     label: "Student Assessment",
  //   //     to: `${adminRoot}/support/faq`,
  //   //     // permission: [UserRole.Admin],
  //   //   },
  //   //   {
  //   //     icon: "simple-icon-chart",
  //   //     label: "Teacher assessment",
  //   //     to: `${adminRoot}/support/ticket`,
  //   //     // permission: [UserRole.Admin],
  //   //   },
  //   // ],
  // },

  {
    id: "children",
    icon: "iconsminds-students",
    label: "My Child/Children",
    to: `${adminRoot}/history`,
    permission: "children",
  },
  // {
  //   id: "cbt",
  //   icon: "iconsminds-students",
  //   label: "CBT",
  //   to: `${adminRoot}/history`,
  //   permission: "cbt",
  // },
  // {
  //   id: "work",
  //   icon: "simple-icon-notebook",
  //   label: "School work",
  //   to: `${adminRoot}/history`,
  //   permission: "work",
  // },
  {
    id: "settings",
    icon: "simple-icon-settings",
    label: "Settings",
    to: `${adminRoot}/support`,
    permission: "settings",
  },
  // {
  //   id: "media",
  //   icon: "iconsminds-video-tripod",
  //   label: "Media",
  //   to: `${adminRoot}/support`,
  //   permission: "media",
  // },
  // {
  //   id: "event",
  //   icon: "simple-icon-event",
  //   label: "Event",
  //   to: `${adminRoot}/support`,
  //   permission: "event",
  // },
  // {
  //   id: "financials",
  //   icon: "iconsminds-financial",
  //   label: "Financials",
  //   to: `${adminRoot}/support`,
  //   permission: "financials",
  // },
  // {
  //   id: "store",
  //   icon: "iconsminds-shop",
  //   label: "My Store",
  //   to: `${adminRoot}/history`,
  //   permission: "store",
  // },
  // {
  //   id: "app",
  //   icon: "iconsminds-shop",
  //   label: "OatStore",
  //   to: `${adminRoot}/history`,
  //   // permission: [UserRole.Teacher],
  // },
];
export default data;
