#Action for depolying oatleaf front-end

name: 🚀 Deploy website on push

on: push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4
        with:
          server: ftp-eu.site4now.net/oatleaf
          username: xenophilya-001
          password: ${{ secrets.SmarterAspFtp }}
